# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  version "5.1.8"

  on_macos do
    on_intel do
      sha256 "2087a9460a666d28a1654bfdd4d1dc5f5e2cc702133304c0593f8254cc9fde10"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "bfe8e20f7d4e2e0a4c2d4aee9dc25e9e7a83305c525d2fb7550995c7e11b486d"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f3759f1e8bee0aca9e1f81ce870021556cc19a2bd4958c7cc809fe5aa7d1fed"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "6b65fa588d046ec8a4ae83fb36c7cb7142db5e8d37e1ec048b81b020bdc334b5"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  name "fox"
  desc "The Forensic Examiner's Swiss Army Knife"
  homepage "https://foxforensics.eu/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-ad.1"
  manpage "fox-cat.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox-time.1"
  manpage "fox.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required

end
