# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  version "4.60.1"

  on_macos do
    on_intel do
      sha256 "4748e5f7b7e848f842bdcfa07afa99b3c5eef18b121e84bc3873785050754da7"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "ca4a401c613d68438bdacfffd0eba4a0551293ad45b577f8e07a705bd130c906"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "8d16ace88bff579a8219fe942e9b55fe288d11a0a5d87712e6ee532f2afc9aaf"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "0ef5ca2affb8bfb269094e0307855c44f609948205829288b9a021748ac8797b"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxforensics.eu/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-ad.1"
  manpage "fox-cat.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required

end
