# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  version "4.60.4"

  on_macos do
    on_intel do
      sha256 "597f04274c940c1b042f73833ae7d876b3a94fe401cd4a61c459229fbbb98b95"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "9ede7f1704e9f44ff4f8243500394922cc7990cce8c24214b2b2be8f7107d47c"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "63c20fb4d2181c5a4e217cc1a5eb4c3ffc20ebd9732f7d77d9330158df7377b1"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
    on_arm do
      sha256 "b088d220bb284b0a9c6220635cdd1df6e61e8a27c1eef1915520739277ed273e"
      url "https://github.com/foxforensics/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/foxforensics/homebrew-fox/"
    end
  end

  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxforensics.eu/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-ad.1"
  manpage "fox-cat.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required

end
